// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2T8CFqXbIYbiO5gKXRegbV6YvpPylVI',
    appId: '1:342790844852:web:441a34be2bc31cb34402e1',
    messagingSenderId: '342790844852',
    projectId: 'hackathon2024-438407',
    authDomain: 'hackathon2024-438407.firebaseapp.com',
    storageBucket: 'hackathon2024-438407.appspot.com',
    measurementId: 'G-L5X6BM5MEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASb2D7cTVu_ZktqL8cGxEu1uEeASgB8I0',
    appId: '1:342790844852:android:6ebe225209ccb53f4402e1',
    messagingSenderId: '342790844852',
    projectId: 'hackathon2024-438407',
    storageBucket: 'hackathon2024-438407.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNhc-NPPMdfjelc9SqJ575lW4vjR2AQY',
    appId: '1:342790844852:ios:c0edb550606ad9094402e1',
    messagingSenderId: '342790844852',
    projectId: 'hackathon2024-438407',
    storageBucket: 'hackathon2024-438407.appspot.com',
    iosBundleId: 'com.example.hackathon2024Pizamka',
  );
}
